### ISSUE TITLE
Oversampling-related issues #1 - "numChannels changed"

### ISSUE THREAD

**Issue by nathanjhood** [nathanjhood/Biquads#11]
Current version: 1.0.4b

Currently, our plugin is fixed to only allow for stereo (essentially dual-mono) processing. While it would be nice to have an entirely flexible bus architecture to support as many channels as the client requests, this is not possible with the current code due to the OS scheme in place.

Our oversampling is initialized in our ProcessWrapper constructor to have 2 channels - a fixed (constant) integer value, with no means of changing this during run-time if desired. The supported busses layouts code has been chosen to reflect this hard-coded channel count, for now.

In order to have channel-extensible oversampling, we would need to have the correct build/initialize/reset mechanisms in place, likely driven by events coming from Audio Processor's "numChannelsChanged()".

The alternative is to restrict the plugin to pre-defined stereo (dual-mono) processing and reflect as such in the literature.

**Comment by StoneyDSP** [comment]
I have now implemented  a forward declaration and back-reference of the BiquadsAudioProcessor derived class within the PluginWrapper structure. This means we have access to getTotalNumInputChannels() and numChannelsChanged() from the base class inside our wrapper.

**Comment by nathanjhood** [comment]
On reflection (been a while), I know that the existing OS implementation is quite hacky; It is not a requirement for the base DSP to work, but rather an extension that further demonstrates some points made in the analysis/write up.

Since *both* open issues are related to the OS implementation, and it is this implementation which is holding back progress somewhat, I've moved that implementation over to a backup branch for visitors to continue referencing, and have updated the main branch to reflect the other latest changes - because I wanted to get multi-platform CI/CD off the ground, above and beyond just oversampling on a Windows-only plugin.

I will "circle back" around to the oversampling at a slightly later date - readers, if curious about this, please check the backup branch for the meantime.
